import pandas as pd

movies = [
    {"id": 1, "title": "Inception", "genre": "Action, Sci-Fi, Thriller", "overview": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", "poster_path": "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg"},
    {"id": 2, "title": "Interstellar", "genre": "Adventure, Drama, Sci-Fi", "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "poster_path": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MvrIdfi1.jpg"},
    {"id": 3, "title": "The Dark Knight", "genre": "Action, Crime, Drama", "overview": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", "poster_path": "https://image.tmdb.org/t/p/w500/qJ2tW6WMOTnwQSBi98FlMACiZ2j.jpg"},
    {"id": 4, "title": "Avengers: Endgame", "genre": "Action, Adventure, Sci-Fi", "overview": "After the devastating events of Infinity War, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.", "poster_path": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg"},
    {"id": 5, "title": "The Matrix", "genre": "Action, Sci-Fi", "overview": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", "poster_path": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg"},
    {"id": 6, "title": "Titanic", "genre": "Drama, Romance", "overview": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "poster_path": "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg"},
    {"id": 7, "title": "Joker", "genre": "Crime, Drama, Thriller", "overview": "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.", "poster_path": "https://image.tmdb.org/t/p/w500/udDclJoHjfpt8QmlCGZHhFUvGfQ.jpg"},
    {"id": 8, "title": "Avatar", "genre": "Action, Adventure, Fantasy", "overview": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.", "poster_path": "https://image.tmdb.org/t/p/w500/kyeqWdyA2x15MffH41YwI19e2qH.jpg"},
    {"id": 9, "title": "Spider-Man: No Way Home", "genre": "Action, Adventure, Fantasy", "overview": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.", "poster_path": "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1Rto0br921P540.jpg"},
    {"id": 10, "title": "La La Land", "genre": "Comedy, Drama, Music", "overview": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", "poster_path": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWkA10F11M080T2K2U8.jpg"},
    {"id": 11, "title": "The Godfather", "genre": "Crime, Drama", "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.", "poster_path": "https://image.tmdb.org/t/p/w500/3bhkrj0eFSt8lD2W2f7vB02wB1T.jpg"},
    {"id": 12, "title": "Pulp Fiction", "genre": "Crime, Thriller", "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", "poster_path": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0IesR1L3B5hBZbkSBB.jpg"},
    {"id": 13, "title": "Fight Club", "genre": "Drama", "overview": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.", "poster_path": "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg"},
    {"id": 14, "title": "Forrest Gump", "genre": "Comedy, Drama, Romance", "overview": "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.", "poster_path": "https://image.tmdb.org/t/p/w500/arw2vGzB04c8fA9Z1D0oYj1LDBx.jpg"},
    {"id": 15, "title": "The Shawshank Redemption", "genre": "Drama", "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.", "poster_path": "https://image.tmdb.org/t/p/w500/9O7gLzmreU0nGkIB1u0a07Kht1x.jpg"},
    {"id": 16, "title": "The Lord of the Rings: The Return of the King", "genre": "Adventure, Fantasy, Action", "overview": "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces.", "poster_path": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTr2.jpg"},
    {"id": 17, "title": "Star Wars: Episode V - The Empire Strikes Back", "genre": "Adventure, Action, Sci-Fi", "overview": "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke.", "poster_path": "https://image.tmdb.org/t/p/w500/2l05cFWJiqVDsL8v42c9k1n9jEE.jpg"},
    {"id": 18, "title": "Gladiator", "genre": "Action, Drama, Adventure", "overview": "In the year 180, the death of emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army's most capable and trusted generals and a key advisor to the emperor.", "poster_path": "https://image.tmdb.org/t/p/w500/t7D10d8TnmAx4EkiB479hVNT2hS.jpg"},
    {"id": 19, "title": "Jurassic Park", "genre": "Adventure, Sci-Fi, Thriller", "overview": "A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA.", "poster_path": "https://image.tmdb.org/t/p/w500/b1xCNnyrPebIc7EWNZIa6jhb1Ww.jpg"},
    {"id": 20, "title": "Back to the Future", "genre": "Adventure, Comedy, Sci-Fi", "overview": "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently interfering with his parents' budding romance and risking his own existence.", "poster_path": "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XPRW0EQqG48nJg3Fq.jpg"}
]

df = pd.DataFrame(movies)
df.to_csv('movies.csv', index=False)
print("movies.csv generated successfully.")
